### ISSUE TITLE
[Bug] "About" link is not working

### ISSUE THREAD

**Issue by NobootRecord** [kiwimoe/kiwimoe.github.io#1]
**Hey there! This is my first submitted GitHub issue, so please do not judge strictly.**

In the top of index.html page, there is "About" link which leads to the _unexisting_ page (https://github.com/Ruzie/about).
As a result I get 404 error.
This is not very critical error, but I would like the website's creator to fix it.
Sorry if I have bad English. Thanks!

![image](https://user-images.githubusercontent.com/80192956/179751614-8d858fdf-8c75-4ce7-91a6-cea4331013f5.png)
![image](https://user-images.githubusercontent.com/80192956/179751670-ff426115-4fb2-45ce-a67c-f649d0a320a5.png)

**Comment by kiwimoe** [comment]
Thanks for letting me know, done, *fixed it*. Should work fine now.

**Comment by NobootRecord** [comment]
Yes, it works! Thanks ;)
